<?php

namespace App\Enum\Email;

enum TemplateIdentifierEnum
{
    case ACCOUNT_ACTIVATION;
    case ACCOUNT_HAS_BEEN_ACTIVATED;

    case EMAIL_ADDRESS_CHANGE_CONFIRMATION;
    case CONFIRM_ACCOUNT_REMOVAL;

    case REQUEST_PASSWORD_RESET_LINK;
    case NEW_PASSWORD_AFTER_REQUEST_CONFIRMATION;

    case AFTER_REGISTER_WELCOME;

    case TRANSACTION_SUCCESSFUL;
    case TRANSACTION_FAILED;

    case TEMPLATE_TEST_EMAIL;
}
