monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels: ["!security"]
        nested:
            type: stream
            path: php://stderr
            level: info
            formatter: monolog.formatter.json
            channels: ["!security"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!security"]
        deduplicated:
            type:    deduplication
            handler: symfony_mailer
            level: critical