parameters:
  message_hub.jwt.lifetime.hours: 1
  message_hub.jwt.user_name: "%project_name_spaceless%"
  message_hub.log.file_path: "%kernel.logs_dir%/%kernel.environment%/message-hub-bridge.log"
  message_hub.log.name: "MessageHubBridge"
